### ISSUE TITLE
fatal: unable to read files to diff

### ISSUE THREAD

**Issue by cowai** [josephfrazier/prettier-diff#1]
```shell
$ prettier-diff 
diff --git a/app-icon.png b/app-icon.png
old mode 100644
new mode 100755
index a4b70c6..1fb3ba1
fatal: unable to read files to diff
```

This happens on all repos I have.

I am using Ubuntu 17.10, and have git version 2.14.1.

**Comment by josephfrazier** [comment]
I think this happens when the underlying [prettier_d](https://github.com/josephfrazier/prettier_d) process dies, but the [~/.prettier_d file](https://github.com/josephfrazier/prettier_d/tree/3306451ff789146243de7365d55418b253fa0c87#how-does-this-work) is still present (this happens when you reboot your machine). Try removing ~/.prettier_d and rerunning prettier-diff.

**Comment by josephfrazier** [comment]
This should be fixed in `v0.0.15` (just published)!

**Comment by cowai** [comment]
Great! Thank you:) You were totally right about it being prettier_d file that was present.

**Comment by josephfrazier** [comment]
Sure thing! I had definitely encountered this problem as well, but just hadn't gotten around to fixing it.

**Comment by sandangel** [comment]
I have the same error with the latest version, could you please confirm?

**Comment by josephfrazier** [comment]
@sandangel 	can you run the following and copy/paste the commands and output here:

```bash
rm ~/.prettier_d
prettier-diff --version
prettier-diff # put your arguments here
```

**Comment by sandangel** [comment]
hi @josephfrazier , there is no prettier-diff --version option.
I do a fresh install with `yarn global add prettier-diff`
```sh
$ yarn global add prettier-diff
yarn global v1.13.0
[1/4] 🔍  Resolving packages...
warning prettier-diff > prettier_d > sinon > nise > text-encoding@0.6.4: no longer maintained
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@vue/cli > @vue/cli-ui > graphql-type-json@0.2.1" has unmet peer dependency "graphql@>=0.8.0".
[4/4] 🔨  Building fresh packages...
success Installed "prettier-diff@0.0.15" with binaries:
      - prettier-diff
      - textconv-prettier
✨  Done in 33.95s.
```
```sh
$ rm -rf ~/.prettier_d
$ prettier-diff --version

error: invalid option: --version
```
```sh
$ prettier-diff f9bef21 # previous commit

nc: invalid option -- q
usage: nc [-46AacCDdEFhklMnOortUuvz] [-K tc] [-b boundif] [-i interval] [-p source_port] [--apple-delegate-pid pid] [--apple-delegate-uuid uuid]
          [-s source_ip_address] [-w timeout] [-X proxy_version]
          [-x proxy_address[:port]] [hostname] [port[s]]
fatal: unable to read files to diff

```

**Comment by josephfrazier** [comment]
```
nc: invalid option -- q
usage: nc [-46AacCDdEFhklMnOortUuvz] [-K tc] [-b boundif] [-i interval] [-p source_port] [--apple-delegate-pid pid] [--apple-delegate-uuid uuid]
          [-s source_ip_address] [-w timeout] [-X proxy_version]
          [-x proxy_address[:port]] [hostname] [port[s]]

```

Ah, this is due to a difference in how `nc` works on Linux vs macOS. Your best bet is to open the `prettier_dnc` script (find it with `which prettier_dnc`) and delete the `-q 0` from the `nc` command options. Let me know how it goes!

I've recently rewritten the `prettier_d` project (on which `prettier-diff` depends) and removed the `prettier_dnc` script, so if I get a chance, I'll likely update `prettier-diff` as well.

**Comment by sandangel** [comment]
hi @josephfrazier I think prettier-diff is using the latest commit from prettier_d 
`package.json`
```json
"prettier_d": "https://github.com/josephfrazier/prettier_d.js",
```

let me try editing the prettier_d script

**Comment by josephfrazier** [comment]
Oh good catch, I had forgotten about that. Yeah I'll probably have to change some things here before it'll work again

**Comment by josephfrazier** [comment]
@cowai I just published version `0.0.16` that uses the `prettier_d` before I made it a fork of Prettier (and removed functionality that `prettier-diff` relies on), so give that a shot. I may move `prettier-diff` into the `prettier_d` repo in order to make it easier to keep in sync with Prettier, but that will have to come later.

**Comment by cowai** [comment]
@josephfrazier 
Which kind of OS and setup do you test on?
I am running Ubuntu 18.04 with nvm.sh @ Node 11.7 ( I have tested several)

``` shell
fs.js:120
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:515:3)
    at tryReadSync (fs.js:338:20)
    at Object.readFileSync (fs.js:375:19)

**Comment by josephfrazier** [comment]
Unfortunately, I'm now on OSX (whereas I developed this on Ubuntu), and I don't currently use `prettier-diff` myself. I need to get TravisCI running here, so we have a good reference for whether things are working...
